#!/usr/bin/env bash
# test-init-harness-scaffold.sh -- tests for lib/init-harness-scaffold.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SCAFFOLD="$SCRIPT_DIR/../lib/init-harness-scaffold.sh"

passed=0
failed=0

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

assert_pass() {
  local name="$1"; shift
  local output
  if output=$("$@" 2>&1); then
    printf '  PASS: %s\n' "$name"
    passed=$((passed + 1))
  else
    printf '  FAIL: %s — exited non-zero: %s\n' "$name" "$output"
    failed=$((failed + 1))
  fi
}

assert_contains() {
  local name="$1" haystack="$2" needle="$3"
  if echo "$haystack" | grep -q -- "$needle"; then
    printf '  PASS: %s\n' "$name"
    passed=$((passed + 1))
  else
    printf '  FAIL: %s — expected to find "%s"\n' "$name" "$needle"
    failed=$((failed + 1))
  fi
}

assert_equals() {
  local name="$1" actual="$2" expected="$3"
  if [ "$actual" = "$expected" ]; then
    printf '  PASS: %s\n' "$name"
    passed=$((passed + 1))
  else
    printf '  FAIL: %s — expected "%s", got "%s"\n' "$name" "$expected" "$actual"
    failed=$((failed + 1))
  fi
}

assert_json_field() {
  local name="$1" json="$2" field="$3"
  local val
  val=$(echo "$json" | jq -r "$field" 2>/dev/null || echo "")
  if [ -n "$val" ] && [ "$val" != "null" ]; then
    printf '  PASS: %s (%s=%s)\n' "$name" "$field" "${val:0:40}"
    passed=$((passed + 1))
  else
    printf '  FAIL: %s — field %s missing or null in JSON\n' "$name" "$field"
    failed=$((failed + 1))
  fi
}

echo "=== Scaffold existence ==="
assert_pass "scaffold file exists" test -f "$SCAFFOLD"
assert_pass "scaffold is executable after chmod" chmod +x "$SCAFFOLD"

PROJECT="$WORK/project"
mkdir -p "$PROJECT"

echo ""
echo "=== Basic execution ==="
OUTPUT=$("$SCAFFOLD" --project-root "$PROJECT" --as-of 2026-04-10 2>/dev/null)
assert_pass "scaffold exits 0" "$SCAFFOLD" --project-root "$PROJECT" --as-of 2026-04-10
assert_json_field "schemaVersion field" "$OUTPUT" ".schemaVersion"
assert_json_field "projectRoot field" "$OUTPUT" ".projectRoot"
assert_json_field "projectName field" "$OUTPUT" ".projectName"
assert_json_field "asOf field" "$OUTPUT" ".asOf"

echo ""
echo "=== Scaffold structure ==="
FILE_COUNT=$(echo "$OUTPUT" | jq -r '.files | length')
assert_equals "six scaffold files emitted" "$FILE_COUNT" "6"
assert_contains "docs directory declared" "$(echo "$OUTPUT" | jq -r '.directories | join(",")')" "docs"
assert_equals "missingCount is six for empty project" "$(echo "$OUTPUT" | jq -r '.missingCount')" "6"
assert_equals "existingCount is zero for empty project" "$(echo "$OUTPUT" | jq -r '.existingCount')" "0"

PATHS=$(echo "$OUTPUT" | jq -r '.files[].path')
assert_contains "AGENTS.md path present" "$PATHS" "^AGENTS.md$"
assert_contains "ARCHITECTURE.md path present" "$PATHS" "^ARCHITECTURE.md$"
assert_contains "docs/PLANS.md path present" "$PATHS" "^docs/PLANS.md$"
assert_contains "docs/RELIABILITY.md path present" "$PATHS" "^docs/RELIABILITY.md$"
assert_contains "docs/SECURITY.md path present" "$PATHS" "^docs/SECURITY.md$"
assert_contains "docs/QUALITY_SCORE.md path present" "$PATHS" "^docs/QUALITY_SCORE.md$"

echo ""
echo "=== Scaffold content ==="
AGENTS_CONTENT=$(echo "$OUTPUT" | jq -r '.files[] | select(.path=="AGENTS.md") | .content')
assert_contains "AGENTS content has generated marker" "$AGENTS_CONTENT" "generated by /signum init --harness"
assert_contains "AGENTS content has frontmatter" "$AGENTS_CONTENT" "^---"
assert_contains "AGENTS content has entry points table" "$AGENTS_CONTENT" "## Agent Entry Points"
assert_contains "AGENTS content uses fixed review date" "$AGENTS_CONTENT" "last_reviewed: 2026-04-10"

ARCH_CONTENT=$(echo "$OUTPUT" | jq -r '.files[] | select(.path=="ARCHITECTURE.md") | .content')
assert_contains "ARCHITECTURE content has components section" "$ARCH_CONTENT" "## Components"

QUALITY_CONTENT=$(echo "$OUTPUT" | jq -r '.files[] | select(.path=="docs/QUALITY_SCORE.md") | .content')
assert_contains "QUALITY_SCORE content has quality dimensions table" "$QUALITY_CONTENT" "## Quality Dimensions"

echo ""
echo "=== Existing file detection ==="
mkdir -p "$PROJECT/docs"
printf '# Existing\n' > "$PROJECT/AGENTS.md"
printf '# Existing\n' > "$PROJECT/docs/SECURITY.md"

OUTPUT_WITH_EXISTING=$("$SCAFFOLD" --project-root "$PROJECT" --as-of 2026-04-10 2>/dev/null)
assert_equals "AGENTS exists detected" \
  "$(echo "$OUTPUT_WITH_EXISTING" | jq -r '.files[] | select(.path=="AGENTS.md") | .exists')" "true"
assert_equals "SECURITY exists detected" \
  "$(echo "$OUTPUT_WITH_EXISTING" | jq -r '.files[] | select(.path=="docs/SECURITY.md") | .exists')" "true"
assert_equals "missingCount updates when files exist" "$(echo "$OUTPUT_WITH_EXISTING" | jq -r '.missingCount')" "4"
assert_equals "existingCount updates when files exist" "$(echo "$OUTPUT_WITH_EXISTING" | jq -r '.existingCount')" "2"

echo ""
echo "=== Results ==="
echo "Passed: $passed"
echo "Failed: $failed"
echo ""

if [ "$failed" -gt 0 ]; then
  echo "FAILED"
  exit 1
else
  echo "ALL PASSED"
fi
