#!/usr/bin/env bash
# init-harness-scaffold.sh -- deterministic harness-doc scaffold for /signum init --harness
# Usage: init-harness-scaffold.sh [--project-root <path>] [--as-of YYYY-MM-DD]
# Output: JSON scaffold metadata + draft contents to stdout
# Exit 0: scaffold generated
# Exit 1: fatal error (missing jq, invalid args)

set -euo pipefail

PROJECT_ROOT="."
AS_OF=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project-root)
      PROJECT_ROOT="$2"
      shift 2
      ;;
    --as-of)
      AS_OF="$2"
      shift 2
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

if ! command -v jq > /dev/null 2>&1; then
  echo '{"error":"jq not found"}' >&2
  exit 1
fi

cd "$PROJECT_ROOT"
ROOT_ABS="$(pwd)"
PROJECT_NAME="$(basename "$ROOT_ABS")"
AS_OF="${AS_OF:-$(date +%F)}"

build_frontmatter() {
  cat <<EOF
---
status: draft
owner: TODO
last_reviewed: ${AS_OF}
review_cadence: quarterly
---
EOF
}

FRONTMATTER="$(build_frontmatter)"

read -r -d '' AGENTS_CONTENT <<EOF || true
${FRONTMATTER}

# AGENTS.md
<!-- generated by /signum init --harness, review and edit before committing -->

## Purpose
- Document the repo surfaces that humans and AI agents are expected to touch.
- Record repo-specific instructions that must override generic coding defaults.
- Keep this file short; link to deeper docs instead of duplicating them.

## Agent Entry Points

| Surface | Path | Role | Owner | Notes |
| --- | --- | --- | --- | --- |
| Primary code surface | TODO | TODO | TODO | What should an agent read first? |
| Runtime / app entrypoint | TODO | TODO | TODO | Binary, API, worker, or job entrypoint |
| CI / release surface | TODO | TODO | TODO | Workflow, deploy, or packaging path |

## Repo-Specific Rules
- TODO: List non-negotiable repo rules (testing, migrations, release gates, rollback expectations).
- TODO: List paths that need specialist review before merge.
- TODO: Link to ARCHITECTURE.md, docs/RELIABILITY.md, and docs/SECURITY.md when a task crosses those boundaries.

## Update Protocol
- Update this file when a new agent-facing surface or rule is introduced.
- Prefer links to deeper docs instead of restating them here.
- Review this file on every major workflow or ownership change.
EOF

read -r -d '' ARCHITECTURE_CONTENT <<EOF || true
${FRONTMATTER}

# ${PROJECT_NAME} — Architecture
<!-- generated by /signum init --harness, review and edit before committing -->

## System Overview
- TODO: Describe the product/system in 2-4 bullets.
- TODO: State the main runtime surfaces (API, worker, CLI, UI, batch jobs).
- TODO: List the current source-of-truth docs and diagrams.

## Components

| Component | Path | Responsibility | Depends On | Notes |
| --- | --- | --- | --- | --- |
| TODO | TODO | TODO | TODO | TODO |

## Critical Flows
- TODO: Request or job lifecycle end-to-end.
- TODO: Data write path and rollback path.
- TODO: Background jobs, queues, or schedulers.

## State and Data
- TODO: Datastores, caches, object storage, search indexes, or message buses.
- TODO: Data ownership boundaries and schemas/contracts that matter most.

## Known Risks
- TODO: Current architectural bottlenecks or hotspots.
- TODO: Areas with high change risk or weak test coverage.
- TODO: Pending migrations, deprecations, or drift to watch.
EOF

read -r -d '' PLANS_CONTENT <<EOF || true
${FRONTMATTER}

# ${PROJECT_NAME} — Plans Index
<!-- generated by /signum init --harness, review and edit before committing -->

## Active Workstreams
- TODO: Link current plans with owner, status, and target date.
- TODO: Mark which plans are blocked and why.

## Decision Log
- TODO: Link ADRs / design notes / research docs that are still active.
- TODO: Record which doc is canonical for roadmap status.

## Review Cadence
- Weekly: TODO
- Monthly: TODO
- Release-bound: TODO

## Archive Rules
- Move completed plans to an archive location instead of deleting them.
- Add a one-line outcome + follow-up debt when closing a plan.
- Keep plan status aligned with shipped reality to avoid doc drift.
EOF

read -r -d '' RELIABILITY_CONTENT <<EOF || true
${FRONTMATTER}

# ${PROJECT_NAME} — Reliability
<!-- generated by /signum init --harness, review and edit before committing -->

## Critical User Journeys
- TODO: List the flows that must keep working for the product to be viable.
- TODO: Link tests, smoke checks, or dashboards that cover each flow.

## Service Levels
- TODO: Define availability / latency / throughput goals if they exist.
- TODO: Record error budgets or acceptable degradation rules.

## Failure Modes and Recovery
- TODO: Top known failure modes.
- TODO: Detection signal for each failure mode.
- TODO: Recovery / rollback procedure for each failure mode.

## Operational Checks
- TODO: Health checks, probes, synthetic tests, or startup checks.
- TODO: Deployment verification checklist.
- TODO: Runbooks and owners.
EOF

read -r -d '' SECURITY_CONTENT <<EOF || true
${FRONTMATTER}

# ${PROJECT_NAME} — Security
<!-- generated by /signum init --harness, review and edit before committing -->

## Trust Boundaries
- TODO: External inputs and untrusted data sources.
- TODO: Internal privileged systems and admin surfaces.
- TODO: Third-party services and what data they receive.

## Secrets and Sensitive Data
- TODO: Where secrets live and how they are rotated.
- TODO: Sensitive data classes handled by the system.
- TODO: Logging / redaction rules.

## Auth and Access Control
- TODO: Authentication methods in use.
- TODO: Authorization model and the most sensitive actions.
- TODO: Break-glass or emergency access procedures.

## Security Review Triggers
- TODO: Changes that require security review.
- TODO: High-risk paths/files/modules.
- TODO: Required evidence before merge for sensitive changes.
EOF

read -r -d '' QUALITY_SCORE_CONTENT <<EOF || true
${FRONTMATTER}

# ${PROJECT_NAME} — Quality Score
<!-- generated by /signum init --harness, review and edit before committing -->

## Definition of Done
- TODO: Minimum test evidence required for a normal change.
- TODO: Documentation / migration / rollback expectations.
- TODO: Cases that require manual verification or staged rollout.

## Quality Dimensions

| Dimension | Minimum Bar | Evidence | Waiver Rule |
| --- | --- | --- | --- |
| Correctness | TODO | TODO | TODO |
| Tests | TODO | TODO | TODO |
| Reliability | TODO | TODO | TODO |
| Security | TODO | TODO | TODO |
| Docs parity | TODO | TODO | TODO |

## Review Policy
- TODO: What blocks merge vs what is warning-only.
- TODO: Which owners must review which classes of change.
- TODO: When to require design review before implementation.

## Audit Trail
- TODO: Where proof artifacts, release notes, and rollback notes live.
- TODO: How exceptions are documented and revisited.
EOF

exists_json() {
  local path="$1"
  if [ -e "$path" ]; then
    printf 'true'
  else
    printf 'false'
  fi
}

AGENTS_EXISTS="$(exists_json "AGENTS.md")"
ARCHITECTURE_EXISTS="$(exists_json "ARCHITECTURE.md")"
PLANS_EXISTS="$(exists_json "docs/PLANS.md")"
RELIABILITY_EXISTS="$(exists_json "docs/RELIABILITY.md")"
SECURITY_EXISTS="$(exists_json "docs/SECURITY.md")"
QUALITY_SCORE_EXISTS="$(exists_json "docs/QUALITY_SCORE.md")"

jq -n \
  --arg schema_version "1.0" \
  --arg project_root "$ROOT_ABS" \
  --arg project_name "$PROJECT_NAME" \
  --arg as_of "$AS_OF" \
  --arg agents_content "$AGENTS_CONTENT" \
  --arg architecture_content "$ARCHITECTURE_CONTENT" \
  --arg plans_content "$PLANS_CONTENT" \
  --arg reliability_content "$RELIABILITY_CONTENT" \
  --arg security_content "$SECURITY_CONTENT" \
  --arg quality_score_content "$QUALITY_SCORE_CONTENT" \
  --argjson agents_exists "$AGENTS_EXISTS" \
  --argjson architecture_exists "$ARCHITECTURE_EXISTS" \
  --argjson plans_exists "$PLANS_EXISTS" \
  --argjson reliability_exists "$RELIABILITY_EXISTS" \
  --argjson security_exists "$SECURITY_EXISTS" \
  --argjson quality_score_exists "$QUALITY_SCORE_EXISTS" \
  '{
    schemaVersion: $schema_version,
    projectRoot: $project_root,
    projectName: $project_name,
    asOf: $as_of,
    writePolicy: "skip-existing-unless-force",
    directories: ["docs"],
    files: [
      {
        path: "AGENTS.md",
        purpose: "Agent-facing repo map and working agreements",
        exists: $agents_exists,
        content: $agents_content
      },
      {
        path: "ARCHITECTURE.md",
        purpose: "High-level system architecture and critical flows",
        exists: $architecture_exists,
        content: $architecture_content
      },
      {
        path: "docs/PLANS.md",
        purpose: "Active plan index and anti-drift planning rules",
        exists: $plans_exists,
        content: $plans_content
      },
      {
        path: "docs/RELIABILITY.md",
        purpose: "Critical journeys, service levels, and recovery notes",
        exists: $reliability_exists,
        content: $reliability_content
      },
      {
        path: "docs/SECURITY.md",
        purpose: "Trust boundaries, sensitive data, and security review triggers",
        exists: $security_exists,
        content: $security_content
      },
      {
        path: "docs/QUALITY_SCORE.md",
        purpose: "Repo-specific quality bars, evidence, and waiver policy",
        exists: $quality_score_exists,
        content: $quality_score_content
      }
    ]
  }
  | .missingCount = ([.files[] | select(.exists == false)] | length)
  | .existingCount = ([.files[] | select(.exists == true)] | length)'
